### ISSUE TITLE
zbus如何不使用内嵌的 zbus 服务

### ISSUE THREAD

**Issue by hsxiaoma** [nutzam/nutzmore#84]
在使用nutz-integration-zbus集成时, 无法使用 js 进行链接, 使用 zbus 官方的服务是可以的. 请问如何办?

**Comment by wendal** [comment]
zbus.server.embed.enable=false

默认也是false

**Comment by hsxiaoma** [comment]
但参考https://www.nutz.cn/yvr/t/rtj7k2gefgi7bqc1ablj6elesj实现以后,使用https://gitee.com/rushmore/zbus-javascript无法连接到服务器.出现400错误. 使用 zbus 原生的程序启动是可以使用 javascript 正常链接的.

**Comment by wendal** [comment]
zbus的服务就应该独立部署的嘛, 内嵌模式是demo用的

**Comment by hsxiaoma** [comment]
## 详细代码如下

```
# zbus.properties
## 共用配置(mq,rpc均需要!!)
zbus.serverAddr=127.0.0.1:15555
zbus.mq.name=nutzbook

## 内嵌zbus服务器端的配置
## 生产环境下请使用独立的zbus注册服务!!!
zbus.server.embed.enable=false

## RPC服务端配置(仅rpc需要)
zbus.rpc.service.enable=false
zbus.rpc.service.consumerCount=2
```

```java
// MainModule
@IocBy(type = ComboIocProvider.class, args = {
        "*js",
        "conf/ioc/",
        // 这个package下所有带@IocBean注解的类,都会登记上
        "*anno","cn.icode.nutz",
        "*tx", // 事务拦截 aop
        "*quartz",
        // 加载zbus插件
        "*zbus","cn.icode.nutz",
        "*async"
}) // 异步执行aop
```

```java
// MainSetup.java
// 获取配置对象
        PropertiesProxy conf = ioc.get(PropertiesProxy.class, "conf");

        // region zbus 的相关代码
        ZBusFactory zbus = ioc.get(ZBusFactory.class, "zbus");
        // 启动内置zbus服务器,通常不需要!!! 尤其是新版zbus支持jvm模式后, 这个选项很少使用了.
        if (conf.getBoolean("zbus.server.embed.enable", false)) {
            ioc.get(MqServer.class);
        }

        // 启动RPC服务端, 若不需要,无需调用
        if (conf.getBoolean("zbus.rpc.service.enable", false)) {
            RpcProcessor rpcProcessor = ioc.get(RpcProcessor.class);
            // 通过buildServices扫描所有标准了@ZBusService的类
            ZBusFactory.buildServices(rpcProcessor, ioc, getClass().getPackage().getName());
            ioc.get(Service.class, "rpcService"); // 注意, Service与服务器连接是异步操作
        }
        // 启动 生产者/消费者(即MQ服务), 若不需要切勿调用.
        zbus.init(getClass().getPackage().getName());

```

```java
// EmailService.java
@ZBusInvoker("emailService")
public interface EmailService {
    boolean send(String to,String subject,String html);
}

// EmailServiceImpl.java

@ZBusService()
@IocBean(name = "emailService")
public class EmailServiceImpl implements EmailService {
    private static final Log log = Logs.get();
    @Inject("refer:$ioc")
    protected Ioc ioc;
    @Override
    public boolean send(String to, String subject, String html) {
         // 实现代码略
    }
}
```

服务器启动后, zbus web 管理界面中并没有出现我注册的服务,  是何解?

**Comment by wendal** [comment]
zbus.rpc.service.enable=false 这样就不注册了吧?

**Comment by wendal** [comment]
rpc才需要注册的吧?

**Comment by hsxiaoma** [comment]
按你所说 zbus.rpc.service.enable=true 也依然不能注册成功.

**Comment by hsxiaoma** [comment]
不开启内置服务器, 下面的注册 rpcService 会报错.

```
Exception in thread "ConsumerThread" Exception in thread "ConsumerThread" org.zbus.mq.MqException: 400: Bad Format, Missing topic
	at org.zbus.mq.Consumer.take(Consumer.java:102)
	at org.zbus.mq.Consumer.take(Consumer.java:122)
	at org.zbus.mq.Consumer$1.run(Consumer.java:221)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wendal** [comment]
zbus的版本对不上

**Comment by hsxiaoma** [comment]
zbus: v0.11.4
nutz-integration-zbus: 1.r.63

**Comment by wendal** [comment]
nutz-integration-zbus: 1.r.63.r5 试试

**Comment by hsxiaoma** [comment]
将 zbus 改为 v0.11.0 也不行.

**Comment by wendal** [comment]
插件版本改1.r.63.r5

**Comment by hsxiaoma** [comment]
插件版本改1.r.63.r5 

Error:(3, 44) java: 程序包org.nutz.integration.zbus.annotation不存在
Error:(5, 2) java: 找不到符号
  符号: 类 ZBusInvoker

**Comment by hsxiaoma** [comment]
1.r.63.r5 里没有 zbus.annotation

**Comment by wendal** [comment]
新版的zbus自带注解, 在接口上标注@Remote就可以了

**Comment by wendal** [comment]
你只使用rpc吗? 因为新版只做了rpc ...

**Comment by hsxiaoma** [comment]
那新版如何在 MainSetup.java 中注册使用呢?

**Comment by hsxiaoma** [comment]
你的 1.r.63.r5 中的 demo 都没有改, 确定你能跑得通吗?

**Comment by wendal** [comment]
并不能, 那是我做nutzboot的时候发现zbus的接口大改, 所以改成现在的样子的

**Comment by hsxiaoma** [comment]
?? 那我想请问一下, 你的 1.r.63 能对上 zbus 的哪个版本呢? 我感觉你用得不是 https://gitee.com/rushmore/zbus 作为开发对象的?

**Comment by wendal** [comment]
那是对应7.2.0的

```xml
		<dependency>
			<groupId>org.zbus</groupId>
			<artifactId>zbus</artifactId>
			<version>7.2.0</version>
		</dependency>
```

**Comment by hsxiaoma** [comment]
我自己手工解决了, 期待你能把示例和文档完善好. 

```java
// MainSetup.java
ServiceBootstrap b = new ServiceBootstrap();
        //手动增加模块，使用默认构造，也可以指定模块细节
        b.addModule(EmailServiceImpl.class);

        try {
            b.serviceName("nutzbook")
                    //.port(15555)  //内部启动了zbus服务器，zbus与rpc服务之间不通过网络协议栈
                    .serviceAddress("localhost:15555")   //也可以通过网络链接到远程服务器上
                    //.ssl("ssl/zbus.crt", "ssl/zbus.key") //启用SSL
                    //.serviceToken("myrpc_service")       //启用Token权限验证
                    .start();
        } catch (Exception e) {
            e.printStackTrace();
        }
```

**Comment by wendal** [comment]
@hsxiaoma 可以发pull request吗?

**Comment by hsxiaoma** [comment]
献上完整使用示例:

1. 下载 [zbus](https://gitee.com/rushmore/zbus/repository/archive/0.11.4-release.zip), 修改 `zbus-dist/bin/zbus.bat(.sh)` 中的 `jdk` 的路径. 
2. 启动 `zbus`. (linux|macos)下请使用 `chmod 777 zbus.sh` 赋权. 

```
# 运行
./zbus.sh 
```

打开浏览器访问 http://localhost:15555

4. 引入 `nutz-integration-zbus`

```xml

 <dependency>
        <groupId>org.nutz</groupId>
        <artifactId>nutz-integration-zbus</artifactId>
        <version>1.r.63.r5</version>
</dependency>
```

5. 修改 `MainSetup.java`

```java
// MainSetup.java
ServiceBootstrap b = new ServiceBootstrap();
//手动增加模块，使用默认构造，也可以指定模块细节
b.addModule(EmailServiceImpl.class);

try {
    b.serviceName("nutzbook")
            //.port(15555)  //内部启动了zbus服务器，zbus与rpc服务之间不通过网络协议栈
            .serviceAddress("localhost:15555")   //也可以通过网络链接到远程服务器上
            //.ssl("ssl/zbus.crt", "ssl/zbus.key") //启用SSL
            //.serviceToken("myrpc_service")       //启用Token权限验证
            .start();
} catch (Exception e) {
    e.printStackTrace();
}
```

6. 修改 `EmailServiceImpl.java`

```java
// EmailServiceImpl.java
@IocBean
public class EmailServiceImpl implements EmailService {
   private static final Log log = Logs.get();
    @Inject("refer:$ioc")
    protected Ioc ioc;

    @Override
    public boolean send(String to, String subject, String html) {
        // 服务是不能正常调用的, 因为 `ioc` 不能通过注入来获取,
        // 需要手工获取一下, 希望解决
        // 这是神马情况啊??? 
        if(ioc == null){
            ioc = Mvcs.ctx().getDefaultIoc();
        }
        log.debug(ioc);
        // 你的业务代码...
    }
}
```

7.  启动 `java`项目, 再浏览 http://localhost:15555 就会看到新注册的服务 

8. 使用 JS 调用 RPC 服务

https://gitee.com/rushmore/zbus-javascript

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title>RpcInvoker Example</title> 
</head>
    <body>

<script src="./zbus.js"></script>   
<script>
var b = new ClientBootstrap(); 
// nutzbook 为注册的 Topic 名称
b.serviceName("nutzbook").serviceAddress("localhost:15555");
var rpc = b.invoker();
rpc.module = 'EmailService'; // 注册的接口名称
function send() {
    return rpc.send('168189878@qq.com', 'js 调用 zbus-RPC 测试邮件','js 调用 zbus-RPC 测试邮件')
}
send().then(function (value) { console.log(value) })
</script> 

    </body>
</html>
```

**Comment by wendal** [comment]
赞

弱弱提一下,可以用pull request的方式吗? 把你的示例放在README内

**Comment by hsxiaoma** [comment]
我没有测试, 我还吃午饭呢, 直是废寝忘食啊. 下午有时间来测试一下.

**Comment by wendal** [comment]
-_- 快去吃饭吧...
