### ISSUE TITLE
json4excel 图片字段的话 读取有问题

### ISSUE THREAD

**Issue by Rekoe** [nutzam/nutzmore#95]
@pangwu86 
```
Exception in thread "main" org.nutz.lang.FailToSetValueException: Fail to set value [] to [com.rekoe.vo.ProductMore]->[image] because 'Fail to cast from <java.lang.String> to <java.io.InputStream> for {}'
	at org.nutz.lang.Mirror.makeSetValueException(Mirror.java:698)
	at org.nutz.lang.Mirror.setValue(Mirror.java:728)
	at org.nutz.integration.json4excel.J4E.rowValue(J4E.java:473)
	at org.nutz.integration.json4excel.J4E.fromSheet(J4E.java:412)
	at com.rekoe.service.ShopifyProductService.main(ShopifyProductService.java:412)
Caused by: org.nutz.castor.FailToCastObjectException: Fail to cast from <java.lang.String> to <java.io.InputStream> for {}
	at org.nutz.castor.Castors.cast(Castors.java:263)
	at org.nutz.castor.Castors.castTo(Castors.java:317)
	at org.nutz.lang.Mirror.setValue(Mirror.java:725)
	... 3 more
Caused by: org.nutz.lang.born.BorningException: Fail to born or cast to 'java.io.InputStream'
 by args: [@()]
 because: No suitable Constructor or Factory Method!!
	at org.nutz.lang.Mirror.born(Mirror.java:1020)
	at org.nutz.castor.castor.String2Object.cast(String2Object.java:16)
	at org.nutz.castor.castor.String2Object.cast(String2Object.java:9)
	at org.nutz.castor.Castors.cast(Castors.java:253)
	... 5 more
```

**Comment by pangwu86** [comment]
需求是 把excel的图片读出来？

**Comment by Rekoe** [comment]
@pangwu86 
暂时的需求 可以不用读取那列的数据 通过 这种方式跳过了
```
public class Image implements J4ECellFromExcel {

	@Override
	public Object fromExcel(Object cellVal) {
		return Streams.nullInputStream();
	}

}
```

**Comment by pangwu86** [comment]
有替代方案就行，默认没有对图片做处理
